# Generated by Django 3.1.7 on 2021-03-31 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Generos:')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Título do Livro:')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='Título do Livro:')),
                ('book_author', models.CharField(blank=True, max_length=200, verbose_name='Autor:')),
                ('book_image', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('book_publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Editora:')),
                ('book_sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse:')),
                ('user_experience', models.TextField(blank=True, null=True, verbose_name='Como foi ler esse livro:')),
                ('user_rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=20, verbose_name='Avaliação')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Genero', to='clube_livro.genero', verbose_name='Gênero do Livro:')),
            ],
        ),
    ]
